// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuP9dMLd4WmT2DRReeCiEgeJ3n2ZL8d6M',
    appId: '1:366900774592:android:5e4b2b94ff6dd5e8c7cf25',
    messagingSenderId: '366900774592',
    projectId: 'onco-connect-785f9',
    storageBucket: 'onco-connect-785f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpAKxB1l8AUo7_AiPhNlpKEPmwmIYrl4',
    appId: '1:366900774592:ios:67776edee82d2abcc7cf25',
    messagingSenderId: '366900774592',
    projectId: 'onco-connect-785f9',
    storageBucket: 'onco-connect-785f9.appspot.com',
    iosBundleId: 'com.application.onco.oncoConnect',
  );
}
